/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ApunteControlador;
import controller.TemaControlador;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ApunteModel;
import model.TemaModel;

/**
 *
 * @author yulia
 */
public class Principal extends javax.swing.JFrame {

    private TemaControlador tctrl;
    private ApunteControlador actrl;
    private String itemCbx;
    /**
     * Creates new form NewJFrame
     */
    public Principal(String item) {
        initComponents();
        this.setLocationRelativeTo(null);
        llenarItems();
        buscadorApunte.setEnabled(false);
        btnApunteAgregar.setEnabled(false);
        this.itemCbx = item;
        comboboxTema.setSelectedItem(item);
        llenarTabla("");
        eliminarApunte();
    }

    public void eliminarApunte(){
    
        JMenuItem eliminar = new JMenuItem("Eliminar");
        jPopupMenu1.add(eliminar);
        tablaApuntes.setComponentPopupMenu(jPopupMenu1);
        
        eliminar.addActionListener(new ActionListener(){   //indica que cuando presionemos el itme de eliminar en el popupmenu este debe de realizar una accion.
            @Override
            public void actionPerformed(ActionEvent e){                 
                try {
                    if(new ApunteControlador().eliminarApunte(tablaApuntes.getValueAt(tablaApuntes.getSelectedRow(), 0).toString()))
                    {
                        JOptionPane.showMessageDialog(null, "Se ha eliminado correctamente!");
                        llenarTabla("");
                    }else{
                        JOptionPane.showMessageDialog(null, "Ha ocurrido un error en la operación.");                
                    }} catch (SQLException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }); 
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaApuntes = new javax.swing.JTable();
        comboboxTema = new javax.swing.JComboBox<>();
        buscadorApunte = new javax.swing.JTextField();
        btnApunteAgregar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnAgregarTema = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("Libro de Notas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tablaApuntes.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        tablaApuntes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Apuntes", "Fecha ingresada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaApuntes.setRowHeight(26);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tablaApuntes, org.jdesktop.beansbinding.ELProperty.create("true"), tablaApuntes, org.jdesktop.beansbinding.BeanProperty.create("autoscrolls"));
        bindingGroup.addBinding(binding);

        tablaApuntes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaApuntesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaApuntes);

        comboboxTema.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        comboboxTema.setForeground(new java.awt.Color(51, 102, 255));
        comboboxTema.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboboxTemaItemStateChanged(evt);
            }
        });

        buscadorApunte.setBackground(new java.awt.Color(255, 255, 204));
        buscadorApunte.setFont(new java.awt.Font("Segoe UI Symbol", 2, 18)); // NOI18N
        buscadorApunte.setForeground(new java.awt.Color(102, 102, 102));
        buscadorApunte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscadorApunteKeyReleased(evt);
            }
        });

        btnApunteAgregar.setBackground(new java.awt.Color(0, 0, 204));
        btnApunteAgregar.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btnApunteAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnApunteAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApunteAgregarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Buscador:");

        btnAgregarTema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar.png")));
        btnAgregarTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTemaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnApunteAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buscadorApunte, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(comboboxTema, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregarTema, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboboxTema, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAgregarTema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buscadorApunte, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApunteAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnApunteAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregarAp.png")));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboboxTemaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboboxTemaItemStateChanged
        if (evt.getStateChange()== ItemEvent.SELECTED ) {            
            if(comboboxTema.getSelectedIndex()!=0){                
                itemCbx = (String)comboboxTema.getSelectedItem();
                //habilitar buscador y btn apunte                
                llenarTabla("");
            }                        
        }
    }//GEN-LAST:event_comboboxTemaItemStateChanged

    private void buscadorApunteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscadorApunteKeyReleased
        resultadoBusqueda(buscadorApunte.getText());
    }//GEN-LAST:event_buscadorApunteKeyReleased

    private void btnAgregarTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTemaActionPerformed
        //abriremos otra ventana para agregar esta mierda        
        Agregartema at = new Agregartema();
        at.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAgregarTemaActionPerformed

    private void btnApunteAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApunteAgregarActionPerformed
        new AgregarApunte(itemCbx).setVisible(true);        
        this.dispose();
    }//GEN-LAST:event_btnApunteAgregarActionPerformed

    private void tablaApuntesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaApuntesMouseClicked
        if(evt.getClickCount()==2){
            String texto = tablaApuntes.getValueAt(tablaApuntes.getSelectedRow(), 0).toString();
            //ir al controlador para luego listar las notas en la ventana siguiente
            
            new VerNotas(texto,itemCbx).setVisible(true);        
            this.dispose();
        }
    }//GEN-LAST:event_tablaApuntesMouseClicked

    private void resultadoBusqueda(String ba){
        llenarTabla(ba);
    }
    
    private void llenarTabla(String bApunte){
        if(!this.itemCbx.isEmpty()){
            buscadorApunte.setEnabled(true);
            btnApunteAgregar.setEnabled(true);
            //obtenemos los datos de la tabla
            actrl = new ApunteControlador();
            ArrayList<ApunteModel> arr = actrl.mostrarApuntes(this.itemCbx,bApunte);
            //limpiar tabla
            limpiarTablaApuntes();
            //llenar tabla
            DefaultTableModel tb=(DefaultTableModel)tablaApuntes.getModel();
            for(ApunteModel aa:arr){
                tb.addRow(new Object[]{aa.getTitulo(), aa.getFecha()});
            }
        }
    }
    
    private void llenarItems(){
        tctrl = new TemaControlador();
        ArrayList<TemaModel> arr = tctrl.obtenerTemas();        
        //listar
        comboboxTema.addItem("Selecciona el Tema");
        for(TemaModel tt:arr){
            comboboxTema.addItem(tt.getTema());
        }
    }
    
    private void limpiarTablaApuntes(){
        DefaultTableModel tb =(DefaultTableModel)tablaApuntes.getModel(); 
        for(int i=tb.getRowCount()-1;i>=0;i--) 
            tb.removeRow(i);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarTema;
    private javax.swing.JButton btnApunteAgregar;
    private javax.swing.JTextField buscadorApunte;
    private javax.swing.JComboBox<String> comboboxTema;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaApuntes;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
